# Git Pre-commit hooks
# Still a work in progress...
# Its hard to find the right balance between speed and functionality

repos:
  # - repo: https://github.com/psf/black
  #   rev: 23.1.0
  #   hooks:
  #     - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [Flake8-pyproject]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: check-json
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: mixed-line-ending
      - id: debug-statements
# Im not sure how to get this to work yet
# - repo: local
#   hooks:
#     - id: Run tests
#       name: Run tests
#       entry: pytest
#       language: system
#       always_run: false
#       args: [tests/]
